apiVersion: batch/v1
kind: Job
metadata:
  name: nomidotwatcher-v1.5-last-50k
  namespace: nodewatcher-staging
  labels:
    stage: staging
    name: nomidotwatcher
    app: nomidotwatcher
    job-name: nomidotwatcher-v1.5-last-50k
spec:
  manualSelector: true
  selector:
    matchLabels:
      stage: staging
      name: nomidotwatcher
      app: nomidotwatcher
      job-name: nomidotwatcher-v1.5-last-50k
  template:
    metadata:
      labels:
        stage: staging
        name: nomidotwatcher
        app: nomidotwatcher
        job-name: nomidotwatcher-v1.5-last-50k
    spec:
      restartPolicy: Never
      containers:
        - name: nomidotwatcher
          image: eu.gcr.io/test-installations-222013/nomidot_watcher@sha256:f88f02e79cfc2c5a8f59ab2fae50f26eda40f1bd7ee4cc8c8b07b194c11d2cee
          imagePullPolicy: Always
          env:
            - name: PRISMA_ENDPOINT
              value: http://nodewatcher-v1-5.nodewatcher-staging:4466
            - name: ARCHIVE_NODE_ENDPOINT
              value: ws://polkassembly-rpc-internal-0.parity-prod.parity.io:9944
            - name: START_FROM
              value: '1100000'
            - name: BLOCK_IDENTIFIER
              value: 'last-50k-1.5'
            - name: MAX_LAG
              value: '10'
          command: ["yarn", "start"]
