image:                             paritytech/kubetools:latest

stages:
  - test
  - dockerize

variables:                         &default-vars
  GIT_DEPTH:                       3
  SIMPLECOV:                       'true'
  KUBE_NAMESPACE:                  "nomidot"
  CI_REGISTRY:                     "paritytech"
  DOCKER_TAG:                      '$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA'

cache:
  key: '${CI_JOB_NAME}'
  paths:
    - node_modules/
    - packages/*/node_modules/

linux-test:
  stage:                            test
  image:                            node:12
  script:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH=$HOME/.yarn/bin:$PATH
    - yarn install --frozen-lockfile
    - yarn build
    - yarn test
    - yarn lint
  tags:
    - linux-docker

#### stage:                        dockerize

.dockerize_init:                   &dockerize_init
  variables:
    <<:                            *default-vars
    DOCKER_DRIVER:                 overlay2
    DOCKER_HOST:                   tcp://localhost:2375
  tags:
    - kubernetes-parity-build
  image:                           docker:git
  services:
    - docker:dind
  before_script:
    - POD_NAME=$(echo ${CI_JOB_NAME} | sed -E 's/^[[:alnum:]:]+-//')
    - export DOCKER_IMAGE="${CI_REGISTRY}/${KUBE_NAMESPACE}-${POD_NAME}"
    - export DOCKER_IMAGE_FULL_NAME=$DOCKER_IMAGE:$DOCKER_TAG
    - echo $DOCKER_IMAGE_FULL_NAME
    - echo "$Docker_Hub_Pass_Parity" | docker login -u "$Docker_Hub_User_Parity" --password-stdin 

dockerize-frontend:
  stage:                           dockerize
  environment:
    name:                          parity-build
  <<:                              *dockerize_init
  script:
    - cd front
    - docker build -t "$DOCKER_IMAGE_FULL_NAME" .
    - docker push "$DOCKER_IMAGE_FULL_NAME"
  only:
    - master
    - tags
    # - /^fv-.*$/

dockerize-server:
  stage:                           dockerize
  environment:
    name:                          parity-build
  <<:                              *dockerize_init
  script:
    - cd back/server
    - cp ../../yarn.lock . && docker build -t "$DOCKER_IMAGE_FULL_NAME" .
    - docker push "$DOCKER_IMAGE_FULL_NAME"
  only:
    - master
    - tags
    # - /^fv-.*$/

dockerize-nodewatcher:
  stage:                           dockerize
  environment:
    name:                          parity-build
  <<:                              *dockerize_init
  script:
    - cd back/node_watcher
    - cp ../../yarn.lock . && docker build -t "$DOCKER_IMAGE_FULL_NAME" .
    - docker push "$DOCKER_IMAGE_FULL_NAME"
  only:
    - master
    - tags
    # - /^fv-.*$/
