apiVersion: v1
kind: Service
metadata:
  name: nomidot-server
  namespace: nomidot-staging
  labels:
    stage: staging
    name: nomidot-server
    app: nomidot-staging
spec:
  loadBalancerIP: 35.189.196.74
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app: nomidot-server
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
