apiVersion: apps/v1
kind: Deployment
metadata:
  name: nomidot-server
  namespace: nomidot-staging
  labels:
    stage: staging
    name: nomidot-server
    app: nomidot-staging
spec:
  selector:
    matchLabels:
      app: nomidot-server
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        stage: staging
        name: nomidot-server
        app: nomidot-server
    spec:
      containers:
        - name: nomidot-server
          image: eu.gcr.io/test-installations-222013/nomidot-server@sha256:5f0f209ff62eb93a3e76a5c406821f4c1a86e88a1ad06e32739241e77893c14e
          env:
            - name: PRISMA_ENDPOINT
              value: http://10.0.9.43:4466
          ports:
            - name: nomidot-4000
              containerPort: 4000
