apiVersion: apps/v1
kind: Deployment
metadata:
  name: nomidot-server
  namespace: nomidot-staging
  labels:
    stage: staging
    name: nomidot-server
    app: nomidot-staging
spec:
  selector:
    matchLabels:
      app: nomidot-server
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        stage: staging
        name: nomidot-server
        app: nomidot-server
    spec:
      containers:
        - name: nomidot-server
          image: eu.gcr.io/test-installations-222013/nomidot_server@sha256:e5704f5b16cb5b24d2f6858c5f5c4e95dc3616580661f8ef6d626d63fe4e86fc
          env:
            - name: PRISMA_ENDPOINT
              value: http://10.0.9.43:4466
          ports:
            - name: nomidot-4000
              containerPort: 4000
