apiVersion: apps/v1
kind: Deployment
metadata:
  name: nomidot-server
  namespace: nomidot-server
  labels:
    stage: staging
    name: nomidot-server
    app: nomidot-server
spec:
  selector:
    matchLabels:
      app: nomidot-server
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        stage: staging
        name: nomidot-server
        app: nomidot-server
    spec:
      containers:
        - name: nomidot-server
          image: eu.gcr.io/test-installations-222013/nomidot_server@sha256:611da4b48329b18aaadc4e44e0301beeb9346b6a4e227ba53be151d360fbdd81
          env:
            - name: PRISMA_ENDPOINT
              value: http://10.0.9.43:4466
          ports:
            - name: nomidot-4000
              containerPort: 4000
