apiVersion: batch/v1
kind: Job
metadata:
  name: fillin-commented
  namespace: nodewatcher-staging
  labels:
    stage: staging
    name: nomidotwatcher
    app: nomidotwatcher
    job-name: fillin-commented
spec:
  manualSelector: true
  selector:
    matchLabels:
      stage: staging
      name: nomidotwatcher
      app: nomidotwatcher
      job-name: fillin-commented
  template:
    metadata:
      labels:
        stage: staging
        name: nomidotwatcher
        app: nomidotwatcher
        job-name: fillin-commented
    spec:
      restartPolicy: Never
      containers:
        - name: nomidotwatcher
          image: eu.gcr.io/test-installations-222013/nomidot_watcher@sha256:815a78318b769ba830b872947052e47daa1f25179cc29bfa246ef79d82542be5
          imagePullPolicy: Always
          env:
            - name: PRISMA_ENDPOINT
              value: http://10.0.9.43:4466
            - name: START_FROM
              value: '1391505'
            - name: BLOCK_IDENTIFIER
              value: 'fillin-commented'
            - name: MAX_LAG
              value: '10'
          command: ["yarn", "start"]
