apiVersion: apps/v1
kind: Deployment
metadata:
  name: nomidotwatcher
  namespace: nodewatcher-staging
  labels:
    stage: staging
    name: nomidotwatcher
    app: nomidotwatcher
spec:
  selector:
    matchLabels:
      app: nomidotwatcher
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        stage: staging
        name: nomidotwatcher
        app: nomidotwatcher
    spec:
      containers:
        - name: nomidotwatcher
          image: eu.gcr.io/test-installations-222013/nomidot_watcher@sha256:3668b66c27e12bd91461d3b43f38cd67d6a367b1e4fa8683603843e2786a4f6d
          env:
            - name: PRISMA_ENDPOINT
              value: http://10.0.9.43:4466
          lifecycle:
            postStart:
              exec:
                command: ["yarn", "start"]
